"""add rules and deviations

Revision ID: 32bf5b5e9e5f
Revises: 4ff8fe192903
Create Date: 2025-12-13 19:19:45.808945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32bf5b5e9e5f"
down_revision: Union[str, None] = "4ff8fe192903"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("rule_type", sa.Enum("NO_MOTION", name="rule_type"), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "deviations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "ACK", "CLOSED", name="deviation_status"),
            nullable=False,
        ),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("subject_key", sa.String(length=200), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_deviations_rule_subject_open",
        "deviations",
        ["rule_id", "subject_key", "status"],
        unique=False,
    )
    op.create_index(
        "ix_deviations_status_last_seen",
        "deviations",
        ["status", "last_seen_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_deviations_status_last_seen", table_name="deviations")
    op.drop_index("ix_deviations_rule_subject_open", table_name="deviations")
    op.drop_table("deviations")
    op.drop_table("rules")
    # ### end Alembic commands ###
